### ISSUE TITLE
So publish it already...

### ISSUE THREAD

**Issue by biggers** [davidhalter/pysible#2]
There's already at least one other project like this.  Yours may have the value of "more simplicity".  But who knows, we can't see it.

thank you.

**Comment by davidhalter** [comment]
I won't for now, it's not in a good state. Sorry. Shitty open source projects don't help the world. :) I think that maintenance of projects is really important. I'm not saying that I won't release it, but for the moment parso and jedi are eating too much of my time already.

There's probably quite a few projects like this one. Haha.

Doing what I did is probably taking you a day or a few. It's not that hard.
